---
sidebar: sidebar 
permalink: rp-reference-roles.html 
keywords: ransomware protection, protect against ransomware attacks, anti-ransomware, role-based access control, rbac, role, permission, access rights, organization,project,account 
summary: 'A proteção contra ransomware do BlueXP  usa o controle de acesso baseado em funções (RBAC) para controlar o acesso que cada usuário tem a recursos e ações específicos. O serviço usa funções específicas da proteção contra ransomware do BlueXP  (RPS).' 
---
= Acesso baseado em funções à proteção contra ransomware da BlueXP  aos recursos
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
A proteção contra ransomware do BlueXP  emprega funções para controlar o acesso que cada usuário tem a recursos e ações específicos.

O serviço usa as funções a seguir específicas da proteção contra ransomware do BlueXP .

* * Administrador de proteção contra ransomware*: Gerencie ações nas guias proteger, Alertas, recuperar, Configurações e relatórios.
* * Visualizador de proteção contra ransomware*: Visualize dados de carga de trabalho, visualize dados de alerta, baixe dados de recuperação e faça download de relatórios.


A plataforma BlueXP  para todos os serviços BlueXP  usa os seguintes tipos de funções:

* *As funções da plataforma* permitem gerenciar usuários, atribuí-los a recursos e dar-lhes funções juntamente com outras ações de toda a plataforma.
+

TIP: Para descoberta na proteção contra ransomware do BlueXP , você deve ter a função *Organization admin* além da função *ransomware protection admin*.

* *As funções de serviços de dados* são limitadas apenas a um serviço de dados específico. Você pode ter várias funções de serviços de dados, dependendo do seu trabalho. A proteção contra ransomware da BlueXP  é um dos serviços de dados da BlueXP .


Para obter detalhes sobre as funções da plataforma, https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html["A documentação de configuração e administração do BlueXP "^] consulte .

A tabela a seguir indica as ações que cada função de proteção de ransomware do BlueXP  pode executar.

[cols="40,20a,20a"]
|===
| Recurso e ação | Administração de proteção contra ransomware | Visualizador de proteção contra ransomware 


| Visualize o painel e todas as guias  a| 
Sim
 a| 
Sim



| No painel, atualize o status da recomendação  a| 
Sim
 a| 
Não



| Inicie o teste gratuito  a| 
Sim
 a| 
Não



| Inicie a descoberta de cargas de trabalho  a| 
Sim
 a| 
Não



| Inicie a redescoberta de cargas de trabalho  a| 
Sim
 a| 
Não



3+| *Na guia proteger*: 


| Adicione, modifique ou exclua planos de proteção  a| 
Sim
 a| 
Não



| Proteja workloads  a| 
Sim
 a| 
Não



| Identificar a exposição a dados confidenciais  a| 
Sim
 a| 
Não



| Listar planos de proteção e detalhes  a| 
Sim
 a| 
Sim



| Listar grupos de proteção  a| 
Sim
 a| 
Sim



| Veja os detalhes do grupo de proteção  a| 
Sim
 a| 
Sim



| Criar, editar ou eliminar grupo de proteçãoão  a| 
Sim
 a| 
Não



| Transferir dados  a| 
Sim
 a| 
Sim



3+| *Na guia Alertas*: 


| Veja alertas e detalhes de alerta  a| 
Sim
 a| 
Sim



| Editar o status do incidente  a| 
Sim
 a| 
Não



| Marcar alerta para recuperação  a| 
Sim
 a| 
Não



| Ver detalhes do incidente  a| 
Sim
 a| 
Sim



| Dispensar ou resolver incentes  a| 
Sim
 a| 
Não



| Bloquear usuário  a| 
Sim
 a| 
Não



| Obtenha a lista completa dos arquivos afetados  a| 
Sim
 a| 
Não



| Transferir dados de alertas  a| 
Sim
 a| 
Sim



3+| *Na guia recuperar*: 


| Transferir ficheiros afetados  a| 
Sim
 a| 
Não



| Restaure o workload  a| 
Sim
 a| 
Não



| Transferir dados de recuperação  a| 
Sim
 a| 
Sim



| Transferir relatórios  a| 
Sim
 a| 
Sim



3+| *Na guia Configurações*: 


| Adicionar ou modificar destinos de cópia de segurança  a| 
Sim
 a| 
Não



| Listar destinos de backup  a| 
Sim
 a| 
Sim



| Ver alvos SIEM conetados  a| 
Sim
 a| 
Sim



| Adicionar ou modificar alvos SIEM  a| 
Sim
 a| 
Não



| Conecte os destinos de segurança da carga de trabalho  a| 
Sim
 a| 
Não



| Ver o status da conexão de segurança da carga de trabalho  a| 
Sim
 a| 
Sim



| Desconete os destinos de segurança da carga de trabalho  a| 
Sim
 a| 
Não



| Configure o exercício de prontidão  a| 
Sim
 a| 
Não



| Inicie o exercício de prontidão  a| 
Sim
 a| 
Não



| Reiniciar o exercício de prontidão  a| 
Sim
 a| 
Não



| Edite o exercício de prontidão  a| 
Sim
 a| 
Não



| Rever o estado do exercício de prontidão  a| 
Sim
 a| 
Sim



| Atualizar configuração de deteção  a| 
Sim
 a| 
Não



| Exibir configuração de descoberta  a| 
Sim
 a| 
Sim



3+| *Na guia relatórios*: 


| Transferir relatórios  a| 
Sim
 a| 
Sim

|===