---
sidebar: sidebar 
permalink: rp-start-faq.html 
keywords: ransomware protection faq, ransomware protection frequently asked questions 
summary: Este FAQ pode ajudar se você está apenas procurando uma resposta rápida para uma pergunta. 
---
= Perguntas frequentes sobre proteção contra ransomware do BlueXP 
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Este FAQ pode ajudar se você está apenas procurando uma resposta rápida para uma pergunta.



== Implantação

* Você precisa de uma licença para usar a proteção contra ransomware BlueXP ?*

Você pode usar os seguintes tipos de licença:

* Inscreva-se para uma avaliação gratuita de 30 dias.
* Compre uma assinatura PAYGO (pay-as-you-go) para os Serviços inteligentes da NetApp e proteção contra ransomware da BlueXP  com o mercado da Amazon Web Services (AWS), o mercado do Google Cloud e o mercado do Microsoft Azure.
* Traga sua própria licença (BYOL), que é um arquivo de licença NetApp (NLF) que você obtém de seu representante de vendas da NetApp Você pode usar o número de série da licença para ativar o BYOL na carteira digital BlueXP .


*Como você ativa a proteção contra ransomware do BlueXP ?* A proteção contra ransomware da BlueXP  não exige capacitação. A opção de proteção contra ransomware é ativada automaticamente na navegação à esquerda do BlueXP .

Para começar, você precisa se inscrever ou entrar em Contato com seu representante de vendas da NetApp para experimentar este serviço. Em seguida, quando você usar o BlueXP  Connector, ele incluirá os recursos apropriados para o serviço.

Para começar a usar a proteção contra ransomware do BlueXP , clique em "Iniciar a descoberta de cargas de trabalho" na página inicial.

*A proteção contra ransomware do BlueXP  está disponível nos modos padrão, restrito e privado?* No momento, a proteção contra ransomware BlueXP  está disponível apenas no modo padrão. Fique atento para mais.

Para obter uma explicação sobre esses modos em todos os serviços BlueXP , https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html["Modos de implantação do BlueXP"^] consulte .



== Acesso

* Qual é a URL de proteção contra ransomware do BlueXP ?* Para o URL, em um navegador, digite: https://console.bluexp.netapp.com/["https://console.bluexp.netapp.com/ransomware-protection"^] Para acessar o console do BlueXP .

*Como as permissões de acesso são tratadas?* https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html["Saiba mais sobre as funções de acesso do BlueXP para todos os serviços"^].

*Qual é a melhor resolução do dispositivo?* A resolução recomendada do dispositivo para a proteção contra ransomware BlueXP  é 1920x1080 ou melhor.

*Qual navegador devo usar?* Qualquer navegador moderno funcionará.



== Interação com outros serviços

*A proteção contra ransomware BlueXP  está ciente das configurações de proteção feitas no NetApp ONTAP?* Sim, a proteção contra ransomware do BlueXP  descobre programações de snapshot definidas no ONTAP.

*Se você definir uma política usando a proteção contra ransomware do BlueXP , você precisa fazer alterações futuras apenas neste serviço?* Recomendamos que você faça alterações de política em relação ao serviço de proteção contra ransomware da BlueXP .

*Como a proteção contra ransomware do BlueXP  interage com o backup e recuperação do BlueXP  e o SnapCenter?*

A proteção contra ransomware da BlueXP  usa os seguintes produtos e serviços:

* Backup e recuperação do BlueXP  para descobrir e definir políticas de snapshot e backup para workloads de compartilhamento de arquivos
* O SnapCenter ou o SnapCenter para VMware podem descobrir e definir políticas de snapshot e backup para workloads de aplicações e VMs.


Além disso, a proteção contra ransomware do BlueXP  usa backup e recuperação do BlueXP  e o SnapCenter / SnapCenter para VMware para executar recuperação consistente com arquivos e workloads.



== Workloads

*O que compõe uma carga de trabalho?* Uma carga de trabalho é uma aplicação, uma VM ou um compartilhamento de arquivos. Um workload inclui todos os volumes usados por uma única instância de aplicação. Por exemplo, uma instância do Oracle DB implantada no ora3.host.com pode ter vol1 e vol2 para seus dados e logs, respetivamente. Esses volumes juntos constituem a carga de trabalho para essa instância específica da instância do Oracle DB.

*Como a proteção contra ransomware do BlueXP  prioriza os dados da carga de trabalho?* A prioridade dos dados é determinada pelas cópias snapshot feitas e pelos backups programados.

A prioridade da carga de trabalho (crítica, padrão, importante) é determinada pelas frequências de instantâneos já aplicadas a cada volume associado à carga de trabalho.

link:rp-use-protect.html["Saiba mais sobre prioridade ou importância da carga de trabalho"].

*Quais cargas de trabalho a proteção contra ransomware BlueXP  é compatível?*

A BlueXP ransomware protection pode identificar as seguintes cargas de trabalho: Oracle, MySQL, compartilhamentos de arquivos, armazenamento em bloco, VMs e datastores de VM.

Além disso, se você estiver usando o SnapCenter ou o SnapCenter para VMware, todas as cargas de trabalho suportadas por esses produtos também serão identificadas na BlueXP ransomware protection, e a BlueXP ransomware protection poderá protegê-las e recuperá-las de maneira consistente com a carga de trabalho.

*Como você associa dados a uma carga de trabalho?*

A proteção contra ransomware da BlueXP  associa dados a um workload das seguintes maneiras:

* A proteção contra ransomware do BlueXP  descobre os volumes e as extensões de arquivos e os associa à carga de trabalho apropriada.
* Além disso, se você tiver o SnapCenter ou o SnapCenter para VMware e tiver workloads configurados no backup e recuperação do BlueXP , a proteção contra ransomware da BlueXP  detetará os workloads gerenciados pelo SnapCenter e SnapCenter para VMware e seus volumes associados.


*O que é uma carga de trabalho "protegida"?* Na proteção contra ransomware do BlueXP , um workload mostra um status "protegido" quando tem uma política de detecção primária habilitada. Por enquanto, isso significa que o ARP está ativado em todos os volumes relacionados à carga de trabalho.

*O que é uma carga de trabalho "em risco"?* Se uma carga de trabalho não tiver uma política de detecção primária habilitada, ela estará "em risco" mesmo que tenha uma política de backup e snapshot habilitada.

*Novo volume adicionado, mas ainda não aparece* se você adicionou um novo volume ao seu ambiente, inicie a descoberta novamente e aplique políticas de proteção para proteger esse novo volume.



== Políticas de proteção

*As políticas de ransomware do BlueXP  coexistem com os outros tipos de políticas de carga de trabalho?* No momento, o backup e a recuperação do BlueXP  (backup em nuvem) são compatíveis com uma política de backup por volume. Portanto, backup e recuperação do BlueXP  e proteção contra ransomware BlueXP  compartilham políticas de backup.

As cópias snapshot não são limitadas e podem ser adicionadas separadamente de cada serviço.

*Quais políticas são necessárias em uma estratégia de proteção contra ransomware?*

As seguintes políticas são necessárias na estratégia de proteção contra ransomware:

* Política de detecção de ransomware
* Política do Snapshot


Não é necessária uma política de backup na estratégia de proteção de ransomware da BlueXP .

*A proteção contra ransomware BlueXP  está ciente das configurações de proteção feitas no NetApp ONTAP?*

Sim, a proteção contra ransomware do BlueXP  descobre as programações de snapshot definidas no ONTAP e se o ARP e o FPolicy estão ativados em todos os volumes em um workload descoberto. As informações que você vê inicialmente no Painel são agregadas de outras soluções e produtos da NetApp.

*A proteção contra ransomware da BlueXP  está ciente das políticas já feitas no backup e recuperação do BlueXP  e no SnapCenter?*

Sim, se você tiver workloads gerenciados no backup e recuperação do BlueXP  ou no SnapCenter, as políticas gerenciadas por esses produtos são trazidas para a proteção contra ransomware do BlueXP .

*Você pode modificar políticas transferidas do backup e recuperação do BlueXP  e/ou do SnapCenter?*

Não, você não pode modificar políticas gerenciadas pelo backup e recuperação do BlueXP  ou pelo SnapCenter na proteção contra ransomware do BlueXP . Você gerencia quaisquer alterações nessas políticas no backup e recuperação do BlueXP  ou no SnapCenter.

*Se existirem políticas do ONTAP (já ativadas no System Manager, como ARP, FPolicy e snapshots), essas políticas são alteradas na proteção contra ransomware BlueXP ?*

Não. A proteção contra ransomware BlueXP  não modifica nenhuma política de deteção existente (ARP, configurações FPolicy) do ONTAP.

*O que acontece se você adicionar novas políticas no backup e recuperação do BlueXP  ou no SnapCenter depois de se inscrever para a proteção contra ransomware do BlueXP ?*

A proteção contra ransomware do BlueXP  reconhece todas as novas políticas criadas no backup e recuperação do BlueXP  ou no SnapCenter.

*Você pode alterar as políticas do ONTAP?*

Sim, você pode alterar as políticas do ONTAP na proteção contra ransomware do BlueXP . Também é possível criar novas políticas na proteção contra ransomware do BlueXP  e aplicá-las a workloads. Essa ação substitui as políticas atuais da ONTAP pelas políticas criadas na proteção contra ransomware do BlueXP .

*Você pode desativar políticas?*

Você pode desativar o ARP em políticas de deteção usando a IU, APIs ou CLI do System Manager.

Você pode desativar as políticas de FPolicy e backup aplicando uma política diferente que não as inclua.
