= Detecte um comportamento anômalo do usuário usando a segurança de workloads de storage do Data Infrastructure Insights
:allow-uri-read: 




=== Detecte um comportamento anômalo do usuário usando a segurança de workloads de storage do Data Infrastructure Insights

Com esta versão, você pode usar a segurança de workload de storage do Data Infrastructure Insights para detectar um comportamento incomum dos usuários em seus workloads de storage. Esse recurso ajuda você a identificar possíveis ameaças à segurança e bloquear usuários potencialmente maliciosos para proteger seus dados.

Para obter detalhes, https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-use-alert.html["Responda a um alerta de ransomware detetado"] consulte .

Antes de usar a segurança de workload de storage para detectar comportamento anômalo do usuário, você precisa configurar a opção usando a opção *Configurações* de proteção contra ransomware da BlueXP .

Consulte a https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-use-settings.html["Configurar as configurações de proteção contra ransomware do BlueXP "].



=== Selecione workloads para descobrir e proteger

Com esta versão, agora você pode fazer o seguinte:

* Em cada conetor, selecione os ambientes de trabalho onde você deseja descobrir cargas de trabalho. Você pode se beneficiar desse recurso se quiser proteger cargas de trabalho específicas em seu ambiente e não em outros.
* Durante a descoberta do workload, é possível habilitar a detecção automática de workloads por conector. Esse recurso permite selecionar as cargas de trabalho que você deseja proteger.
* Descubra cargas de trabalho recém-criadas para ambientes de trabalho selecionados anteriormente.


Consulte a https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-start-discover.html["Localizar workloads"].
