= Suporte de carga de trabalho SAN
:allow-uri-read: 




=== Suporte de carga de trabalho SAN

Esta versão inclui suporte para cargas de trabalho SAN na BlueXP ransomware protection. Agora você pode proteger cargas de trabalho SAN, além de cargas de trabalho NFS e CIFS.

Para obter mais informações, link:https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-start-prerequisites.html["Pré-requisitos de proteção contra ransomware da BlueXP "]consulte .



=== Proteção de carga de trabalho aprimorada

Esta versão aprimora o processo de configuração para cargas de trabalho com políticas de snapshot e backup de outras ferramentas da NetApp , como o SnapCenter ou o BlueXP backup and recovery. Em versões anteriores, a BlueXP ransomware protection detectava as políticas de outras ferramentas, permitindo apenas que você alterasse a política de detecção. Com esta versão, agora você pode substituir as políticas de snapshot e backup pelas políticas de BlueXP ransomware protection ou continuar usando as políticas de outras ferramentas.

Para obter detalhes, link:https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-use-protect.html["Proteja workloads"]consulte .



=== Notificações por e-mail

Se a BlueXP ransomware protection detectar um possível ataque, uma notificação aparecerá nas Notificações do BlueXP e um e-mail será enviado para o endereço de e-mail que você configurou.

O e-mail inclui informações sobre a gravidade, a carga de trabalho impactada e um link para o alerta na guia *Alertas* da BlueXP ransomware protection .

Se você configurou um sistema de gerenciamento de segurança e eventos (SIEM) na BlueXP ransomware protection, o serviço envia detalhes de alerta para seu sistema SIEM.

Para obter detalhes, link:https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-use-alert.html["Lidar com alertas de ransomware detectados"]consulte .
