= Atualizações da página de destino
:allow-uri-read: 




=== Atualizações da página de destino

Esta versão inclui atualizações na página inicial da proteção contra ransomware BlueXP, o que facilita o início do teste gratuito e a descoberta.



=== Atualizações de exercícios de prontidão

Anteriormente, era possível executar um exercício de prontidão para ransomware simulando um ataque a uma nova carga de trabalho de amostra. Com este recurso, você pode investigar o ataque simulado e recuperar a carga de trabalho. Use este recurso para testar notificações de alerta, resposta e recuperação. Execute e agende esses exercícios com a frequência necessária.

Com esta versão, você pode usar um novo botão no Painel de proteção contra ransomware do BlueXP para executar um exercício de prontidão para ransomware em uma carga de trabalho de teste, facilitando a simulação de ataques de ransomware, a investigação de seu impacto e a recuperação de cargas de trabalho de forma eficiente, tudo dentro de um ambiente controlado.

Agora você pode executar exercícios de prontidão em cargas de trabalho CIFS (SMB), além de cargas de trabalho NFS.

Para obter detalhes, https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-start-simulate.html["Faça um exercício de prontidão para ataques de ransomware"] consulte .



=== Habilitar atualizações de classificação do BlueXP

Antes de usar a classificação do BlueXP  no serviço de proteção contra ransomware da BlueXP , você precisa habilitar a classificação do BlueXP  para Escanear seus dados. Classificar dados ajuda você a encontrar informações de identificação pessoal (PII), o que pode aumentar os riscos de segurança.

Você pode implementar a classificação BlueXP em uma carga de trabalho de compartilhamento de arquivos a partir da proteção contra ransomware BlueXP. Na coluna *Exposição de privacidade*, selecione a opção *Identificar exposição*. Se você habilitou o serviço de classificação, esta ação identifica a exposição. Caso contrário, com esta versão, uma caixa de diálogo apresenta a opção de implementar a classificação BlueXP. Selecione *Implantar* para acessar a página inicial do serviço de classificação BlueXP, onde você pode implementar esse serviço. W

Para mais detalhes, consulte  https://docs.netapp.com/us-en/bluexp-classification/task-deploy-cloud-compliance.html["Implante a classificação do BlueXP  na nuvem"^] e para usar o serviço dentro da proteção contra ransomware BlueXP, consulte  https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-use-protect-classify.html["Procure informações pessoalmente identificáveis com a classificação BlueXP "] .
